export const FEATURES = [
    {
        title: "Cursor Mask Reveal",
        desc: "Create a spectacular spotlight mask reveal effect driven by cursor movement, exposing hidden background graphics or layers upon hover.",
        url: "https://framer.com/m/CursorMaskReveal-MSVA.js@5e7PeYzw1lgcGpdKBA03",
        moduleId: "CursorMaskReveal-MSVA.js",
        iconName: "Eye",
    },
    {
        title: "Glow Card",
        desc: "An ultra-premium card with a dynamic radial hover glow border. The glowing light follows your cursor's exact coordinates in real-time.",
        url: "https://framer.com/m/Glow-Card-m4qh.js@xTXGQutxuYVtwabuhfCz",
        moduleId: "Glow-Card-m4qh.js",
        iconName: "Sparkles",
    },
    {
        title: "3D Interactive Book",
        desc: "A stunning three-dimensional book layout that realistically opens, turns pages, and closes upon scroll or direct click interaction.",
        url: "https://framer.com/m/Book-AFRs.js@mxOP9zughWqzCr7yH17p",
        moduleId: "Book-AFRs.js",
        iconName: "BookOpen",
    },
    {
        title: "3D Flip Card",
        desc: "A high-fidelity 3D flip card with realistic physics-based spatial depth and hover rotations, perfect for interactive bios or products.",
        url: "https://framer.com/m/FlipCard-component-bDbX.js@IgCJCjQg25fKVg7qOlHu",
        moduleId: "FlipCard-component-bDbX.js",
        iconName: "RefreshCw",
    },
    {
        title: "Image Mask Text",
        desc: "Mask a beautiful scrolling or playing high-resolution image sequence directly inside bold typographic font layers for artistic headers.",
        url: "https://framer.com/m/ImageMaskText-w8kR.js@6HKto33BXoCd8V6GAs1H",
        moduleId: "ImageMaskText-w8kR.js",
        iconName: "Type",
    },
    {
        title: "Mouse Mascot Trail",
        desc: "A charming smiling green mascot (like our signature apple mascot) that follows the user's cursor with fluid spring physics and trails.",
        url: "https://framer.com/m/Mouse-trail-q6Fq.js@VTKySs2XVK542u5K0zaJ",
        moduleId: "Mouse-trail-q6Fq.js",
        iconName: "MousePointerClick",
    },
    {
        title: "Polaroid Photo Ticker",
        desc: "A vintage Polaroid photo frame slider that cycles through images or tech brand logos with authentic physics-based wiggle animations.",
        url: "https://framer.com/m/PolaroidTicker-cVLI.js@ME0RAld2LYtGMiVxLyIs",
        moduleId: "PolaroidTicker-cVLI.js",
        iconName: "Image",
    },
    {
        title: "Smooth Text Carousel",
        desc: "An infinitely looping typographic carousel with customizable text sizes, speeds, and directions, designed for clean tickers.",
        url: "https://framer.com/m/Text-Carousel-Igq7.js@2OAw8ZMDoCKGGDVhFnuE",
        moduleId: "Text-Carousel-Igq7.js",
        iconName: "Sliders",
    },
    {
        title: "Scroll Image Sequence",
        desc: "High-performance scroll-driven frame-by-frame image sequence playback, creating cinematic storytelling transitions as users scroll.",
        url: "https://framer.com/m/ImageSequence-IJSj.js@6G3H6mdZZNPIcZXzNhhsbuikd",
        moduleId: "ImageSequence-IJSj.js",
        iconName: "Film",
    },
];
