export const TESTIMONIALS = [
    {
        name: "Sarah Mitchell",
        role: "CEO",
        company: "TechStart Innovations",
        companyUrl: "https://techstart.com",
        image: "/images/testimonials/person1.jpg",
        content: "They shipped in weeks what two other vendors quoted us months for — and it looked better.",
        time: "3:45 PM",
        date: "Dec 15, 2025",
    },
    {
        name: "David Chen",
        role: "Founder",
        company: "GrowthLabs",
        companyUrl: "https://growthlabs.com",
        image: "/images/testimonials/person2.jpg",
        content: "We came for a website and realized they could build the whole product. They did.",
        time: "11:10 AM",
        date: "Nov 28, 2025",
    },
    {
        name: "Emily Rodriguez",
        role: "Marketing Director",
        company: "BrandFlow",
        companyUrl: "https://brandflow.com",
        image: "/images/testimonials/person3.jpg",
        content: "The AI calling actually works. Our front desk hasn't been the same since.",
        time: "9:30 AM",
        date: "Oct 20, 2025",
    },
    {
        name: "Michael Park",
        role: "CTO",
        company: "FinTech Solutions",
        companyUrl: "https://fintechsol.com",
        image: "/images/testimonials/person4.jpg",
        content: "One team for design, code, and AI meant no finger-pointing and no delays — just a product that shipped.",
        time: "2:00 PM",
        date: "Sep 12, 2025",
    },
    {
        name: "Jessica Williams",
        role: "Product Manager",
        company: "CloudVenture",
        companyUrl: "https://cloudventure.com",
        image: "/images/testimonials/person1.jpg",
        content: "Weekly demos, real progress, zero big-reveal drama. We always knew exactly where things stood.",
        time: "4:15 PM",
        date: "Aug 5, 2025",
    },
    {
        name: "Robert Kumar",
        role: "Head of Operations",
        company: "DataStream Corp",
        companyUrl: "https://datastream.com",
        image: "/images/testimonials/person2.jpg",
        content: "They put AI into the parts of our business that needed it — and skipped the parts that didn't.",
        time: "1:20 PM",
        date: "Jul 18, 2025",
    },
];
